DjangoVenv/root@159.223.80.238/Wristband/urls.py
from django.contrib import admin
from django.urls import path
from wed import views 

urlpatterns = [
        path('admin/', admin.site.urls),
        path('id/', views.index),
        path('data/', views.Input),
        path('qrcode/', views.Save),
]

DjangoVenv/root@159.223.80.238/wed/models.py
from distutils.command.upload import upload
from django.db import models
from django.contrib.auth.models import UserManager

# Create your models here.
GENDER_choice = (
    ('female', 'หญิง'),
    ('male', 'ชาย'),
    ('other', 'อื่น ๆ')
)
Blood_Group = {
    ('ab', 'AB'),
    ('a','A'),
    ('b','B'),
    ('o','O'),
}

class Wb(models.Model):

    elder_name = models.CharField("ชื่อ",max_length=50, blank=True, null=True)
    elder_surname = models.CharField("นามสกุล",max_length=50, blank=True, null=True)
    elder_id = models.CharField("เลข ID", max_length=7, primary_key=True)
    elder_nickname = models.CharField("ชื่อเล่น",max_length=50, blank=True, null=True)
    elder_gender = models.CharField("เพศ",max_length=50, choices= GENDER_choice, blank=True, null=True)
    elder_birth = models.DateField("วันเกิด",blank=True, null=True)
    elder_age = models.SmallIntegerField("อายุ",blank=True, null=True)
    elder_weight = models.CharField("น้ำหนัก",max_length=50, blank=True, null=True)
    elder_height = models.CharField("ส่วนสูง",max_length=50, blank=True, null=True)
    elder_blood = models.CharField("กรุ๊ปเลือด",max_length=7,choices= Blood_Group, blank=True, null=True)
    elder_disease = models.CharField("โรคประจำตัว",max_length=50, blank=True, null=True)
    elder_food = models.CharField("อาหารที่แพ้",max_length=50, blank=True, null=True)
    elder_medicine = models.CharField("ยาที่แพ้",max_length=50, blank=True, null=True)
    elder_useMedicine = models.CharField("ยาที่ใช้ประจำ",max_length=50, blank=True, null=True)
    elder_address = models.TextField("ที่อยู่",blank=True, null=True)
    elder_cure = models.TextField("การรักษา",blank=True, null=True)
    elder_help = models.TextField("การให้ความช่วยเหลือ",blank=True, null=True)
    elder_phone = models.CharField("เบอร์โทร",max_length=50, blank=True, null=True)
    elder_fb = models.CharField("Facebook",max_length=50, blank=True, null=True)
    elder_line = models.CharField("Line",max_length=50, blank=True, null=True)
    elder_song = models.CharField("เพลงที่ชอบ",max_length=50, blank=True, null=True)
    elder_actor = models.CharField("ดาราที่ชอบ",max_length=50, blank=True, null=True)
    elder_movie = models.CharField("ภาพยนตร์ที่ชอบ",max_length=50, blank=True, null=True)
    profile_img = models.ImageField("รูปโปรไฟล์", upload_to="./profile_img/", null=True)

    objects = UserManager()


    class Meta:
        db_table = "wb"

    def __str__(self):
        return self.elder_id + " " + self.elder_name

DjangoVenv/root@159.223.80.238/wed/forms.py
from dataclasses import field
from django import forms
from django.forms import widgets
from .models import Wb

class WedForm(forms.ModelForm):
    class Meta:
        model = Wb
        fields = "__all__"
        
        widgets = {
            'elder_birth': widgets.DateInput(attrs={'type': 'date'}),
            'elder_ID': forms.TextInput(attrs={'class' : 'form-control', 'placeHolder' : 'ID'}),
            'elder_name': forms.TextInput(attrs={'class' : 'form-control', 'placeHolder' : 'name'}),
            'elder_surname': forms.TextInput(attrs={'class' : 'form-control', 'placeHolder' : 'surname'}),
            'elder_nickname': forms.TextInput(attrs={'class' : 'form-control', 'placeHolder' : 'nickname'}),
            'elder_gender': forms.Select(attrs={'class' : 'form-control'}),
            'elder_age': forms.TextInput(attrs={'class' : 'form-control', 'placeHolder' : 'age'}),
            'elder_weight': forms.TextInput(attrs={'class' : 'form-control', 'placeHolder' : 'weight'}),
            'elder_height': forms.TextInput(attrs={'class' : 'form-control', 'placeHolder' : 'height'}),
            'elder_blood' : forms.Select(attrs={'class' : 'form-control'})
        }

DjangoVenv/root@159.223.80.238/wed/views.py
from django.shortcuts import render
from wed.models import Wb
from .forms import Wb, WedForm
import qrcode
import qrcode.image.svg
from io import BytesIO

# Create your views here.

def Save(request):
    context = {}   
    if request.method == "POST":
        factory = qrcode.image.svg.SvgImage
        img = qrcode.make(request.POST.get("qr_text","www.google.com"), image_factory=factory, box_size=20)
        stream = BytesIO()
        img.save(stream)
        context["svg"] = stream.getvalue().decode()

    return render(request, "home.html", context=context)

  
def Input(request):  
    context = {}
    form = WedForm(request.POST)
    # print(form)
    # print("HELLO 1 ")

    print(form.is_valid())
    if request.method == "POST":
        form = WedForm(request.POST or None ,request.FILES or None)
        print("Hello 1")
        if form.is_valid():
            print("Hello 2")
            form.save()
            print("Hello 3")
    else:
        form = WedForm()
    # print(form.is_valid())
    # if form.is_valid():
    #     # save the form data to model
    #     value = form.cleaned_data("elder_surname")
    #     print(value)
    #     print("HELLO 2 ")
    #     form.save()
    #     print("HELLO 3 ")
    # else:
    #     print("Form is not valid")
    #     form = WedForm()
    
    context['form'] = form
    return render(request, "data.html", context)  

def index(request):

   elder_code = request.GET['elder']
   elder_query = Wb.objects.get(elder_id = elder_code)

   context = {
        "elder" : elder_query,
        "profile_img" : elder_query.profile_img.name[10:]
   }
   return render(request, "index.html", context)

DjangoVenv/root@159.223.80.238/wed/templates/data.html
{% load static %}
<!DOCTYPE html>  
<html lang="en">  
    <head> 
        <meta charset="UTF-8">  
        <title>INPUT YOUR INFORMATION</title>
        <link rel="stylesheet" href="{% static '/assets/css/style3.css' %}"/>  
        <link rel="icon" href="#">
    </head>  
    <body>  
        <div class = "header" id="name" >
            กรอกข้อมูล
        </div>
        <form method="post" class="post-form" enctype="multipart/form-data" action="/qrcode"> 
            <input type="hidden" name="csrfmiddlewaretoken" value="eL3HkWyC0yeKoniMLAdDfuHp2gVjYMDRinYg6A0X8CQee1YfL5eahpTsOGmoroIL">  
            
        <div class = "square">
            <br>
            <div style="font-size: 30px; font-family: Sukhumvit Set; font-weight: 600;color: white;text-align: center;">ข้อมูลส่วนตัว</div>
            <br>

                    <div class = "inPersonal">
                        <label for="id_elder_name">ชื่อ :</label> <input style="margin-left: 58px;" type="text" name="elder_name" placeHolder="name" maxlength="50" id="id_elder_name">
                    </div>

                    <div class = "inPersonal">
                        <label for="id_elder_surname">นามสกุล :</label> <input type="text" name="elder_surname" placeHolder="surname" maxlength="50" id="id_elder_surname">
                    </div>

                    <div class = "inPersonal">
                        <label for="id_elder_id">เลข ID :</label> <input style="margin-left: 23px;" type="text" name="elder_id" maxlength="7" placeHolder="id" required id="id_elder_id">
                    </div>


                    <div class = "inPersonal">
                        <label for="id_elder_gender">เพศ :</label> 
                        <select name="elder_gender" id="id_elder_gender" style="width: 250px; height: 50px; border-radius: 10px;margin-left: 48px;">
                            <option style="text-align: center;" value="" selected>--------------------</option>
                            <option style="text-align: center;" value="female">หญิง</option>
                            <option style="text-align: center;" value="male">ชาย</option>
                            <option style="text-align: center;" value="male">อื่น ๆ</option>
                        </select>
                    </div>

                    <div class = "inPersonal">
                        <label for="id_elder_nickname">ชื่อเล่น :</label> <input style="margin-left: 23px;" type="text" name="elder_nickname" placeHolder="nickname" maxlength="50" id="id_elder_nickname">
                    </div>

                    <div class = "inPersonal">
                        <label for="id_elder_birth">วันเกิด :</label> <input style="text-align: center; font-family: Sukhumvit Set;margin-left: 23px;" type="date" name="elder_birth" id="id_elder_birth">
                    </div>

                    <div class = "inPersonal">
                        <label for="id_elder_age">อายุ :</label> <input style="margin-left: 48px;margin-bottom: 50px;" type="text" name="elder_age" placeHolder="age" id="id_elder_age">
                    </div>

        </div>
        <br>
        <br>

        <div class = "square">
            <br>
            <div style="font-size: 30px; font-family: Sukhumvit Set; font-weight: 600;color: white;text-align: center;">ข้อมูลสุขภาพ</div>
            <br>

                    <div class = "inPersonal">
                        <label for="id_elder_weight">น้ำหนัก:</label> <input style="margin-left: 52px;" type="text" name="elder_weight" placeHolder="weight" maxlength="50" id="id_elder_weight">
                    </div>

                    <div class = "inPersonal">
                        <label for="id_elder_height">ส่วนสูง:</label> <input style="margin-left: 52px;" type="text" name="elder_height"placeHolder="height" maxlength="50" id="id_elder_height">
                    </div>

                    <div class = "inPersonal">
                        <label for="id_elder_blood">กรุ๊ปเลือด:</label> 
                    <select name="elder_blood"id="id_elder_blood" style="width: 250px; height: 50px; border-radius: 10px;margin-left: 30px;">
                        <option style="text-align: center;" value="" selected>---------</option>
                        <option value="ab">AB</option>
                        <option value="a">A</option>
                        <option value="b">B</option>
                        <option value="o">O</option>
                    </select>
                    </div>

                    <div class = "inPersonal">
                        <label for="id_elder_disease">โรคประจำตัว:</label> <input type="text" name="elder_disease" maxlength="50" id="id_elder_disease">
                    </div>
                    
                    <div class = "inPersonal">
                        <label for="id_elder_food">อาหารที่แพ้:</label> <input style="margin-left: 15px;"type="text" name="elder_food" maxlength="50" id="id_elder_food">
                    </div>

                    <div class = "inPersonal">
                        <label for="id_elder_medicine">ยาที่แพ้:</label> <input style="margin-left: 52px;" type="text" name="elder_medicine" maxlength="50" id="id_elder_medicine">
                    </div>

                    <div class = "inPersonal">
                        <label for="id_elder_useMedicine">ยาที่ใช้ประจำ:</label> <input type="text" name="elder_useMedicine" maxlength="50" id="id_elder_useMedicine">
                    </div>

                    <div class = "inPersonal">
                        <label for="id_elder_cure">การรักษา:</label>
                    </div>
                    <center><textarea name="elder_cure" cols="40" rows="10" id="id_elder_cure">
                    </textarea></center>

                    <div class = "inPersonal">
                        <label for="id_elder_help">การให้ความช่วยเหลือ:</label>
                    </div>
                    <center><textarea name="elder_help" cols="40" rows="10" id="id_elder_help">
                    </textarea></center>
                    <br>
                    <br>
        </div>

        <br><br>


        <div class = "square">
            <br>
            <br>
            <div style="font-size: 30px; font-family: Sukhumvit Set; font-weight: 600;color: white;text-align: center;">ช่องทางติดต่อ</div>

            <div class = "inPersonal">
                <label for="id_elder_address">ที่อยู่:</label> <textarea name="elder_address" cols="40" rows="10" id="id_elder_address">
                </textarea>
            </div>

            <div class = "inPersonal">
                <label for="id_elder_phone">เบอร์โทร:</label> <input style="margin-left: 28px;" type="text" name="elder_phone" maxlength="50" id="id_elder_phone">
            </div>

            <div class = "inPersonal">
                <label for="id_elder_fb">Facebook:</label> <input style="margin-left: 7px;"type="text" name="elder_fb" maxlength="50" id="id_elder_fb">
            </div>

            <div  class = "inPersonal">
                <label for="id_elder_line">Line:</label> <input style="margin-left: 64px;" type="text" name="elder_line" maxlength="50" id="id_elder_line">
            </div>

            <div  class = "inPersonal">
                <label for="id_elder_song">เพลงที่ชอบ:</label> <input type="text" name="elder_song" maxlength="50" id="id_elder_song">
            </div>

            <div  class = "inPersonal">
                <label for="id_elder_actor">ดาราที่ชอบ:</label> <input type="text" name="elder_actor" maxlength="50" id="id_elder_actor">
            </div>

            <div  class = "inPersonal">
                <label for="id_elder_movie">ภาพยนตร์ที่ชอบ:</label> 
            </div>
            <center style="margin-left: 40px"><input type="text" name="elder_movie" maxlength="50" id="id_elder_movie"></center>

            <div  class = "inPersonal">
                <label for="id_profile_img">รูปโปรไฟล์:</label> <input type="file" name="profile_img" accept="image/*" required id="id_profile_img">
            </div>

            <div>
                <center><button type="submit" class="button default" style="border-radius: 15px;width: 150px;height: 50px;font-size: 20px;font-family: Sukhumvit Set;">Save</button></center>  
            </div>
            <br>
            <br>
        </div>



        </form>  
    </body>  
</html>  

DjangoVenv/root@159.223.80.238/wed/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>QR Code Generator</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css"
        rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6"
        crossorigin="anonymous">
</head>
    <body>
        <div class="container shadow" style="width: 800px; margin-top: 5em; padding: 2em">
            <form method="post">
                {% csrf_token %}
            </form>
            <div class="input-group mb-3">
                <div class="input-group mb-3">
                    <p style="margin: auto;"> Website ของคุณ : 127.0.0.1:8080/id/?elder==elder_id </p>
                </div>
                
                    <div style="margin: auto;">
                        {{ svg|safe }}
                    </div>
                <div class="input-group mb-3">
                    <input type="submit" value="กดเพื่อสร้าง QR Code" style="max-width: 200px; margin: auto; border-color: black;border-radius: 10px;" class="form-control" >
                </div>
            </div>
        </div>
    </body>
</html>

DjangoVenv/root@159.223.80.238/wed/templates/index.html
{% load static %}
<!DOCTYPE html>
<html>

    <head>
        <meta charset="utf-8">
        <title>WED</title>
        <link rel="stylesheet" href="{% static '/assets/css/style1.css' %}"/>
    </head>

        <body>
        
        <div class="header">
          <div class="header-right">
                <img src="{% static '/assets/img/Logo.png' %}" alt="logo" width="130" height="130" style="margin-top: 10px;">
          </div>
          <div id="name" style="margin-left: 150px; margin-top: 20px;">WED</div>
        </div>

       <div class = "OnTheLeft" >
           <div style="margin-bottom: 30px;">
                <img src="{% get_static_prefix %}{{ profile_img }}" alt="logo" width="300" height="300">
           </div>
           <div id="rcorner-name">
                <div class = "pull-name">
                    {{elder.elder_name}} {{elder.elder_surname}}
                </div>
            </div>
            <div id="rcorner-left">
                <div class="pull-left">
                    <img src="{% static '/assets/img/facebook.png' %}" alt="logo" width="45" height="45"style="margin-left: 3px; margin-top: 2px;"> 
                </div>
                <div class = "pull-inLeft">
                    {{elder.elder_fb}}
                </div>
            </div>
            <div id="rcorner-left">
                <div class="pull-left">
                    <img src="{% static '/assets/img/line.png' %}" alt="logo" width="50" height="50"> 
                </div>
                <div class = "pull-inLeft">
                    <div style="margin-right: 50px;">{{elder.elder_line}}</div>
                </div>
            </div>
            <div id="rcorner-left">
                <div class="pull-left">
                    <img src="{% static '/assets/img/phone2.png' %}" alt="logo" width="45" height="45" style="margin-left: 3px; margin-top: 3px;"> 
                </div>
                <div class = "pull-inLeft">
                    <div style="margin-right: 50px;">{{elder.elder_phone}}</div>
                </div>
            </div>
       </div>

        <div class = "OnTheRight" >
           <div id="rcorner-sos">
                แจ้งเหตุฉุกเฉิน
           </div>
            <div class = "pull-left" style="font-family: 'Sukhumvit Set'; line-height: 85px; margin-left: 100px; font-size: 40px; font-weight: 500; color: white;">
                ข้อมูลสุขภาพ
            </div>
            <div>
                <img src="{% static '/assets/img/hospital.png' %}" alt="logo" width="50" height="50" style="margin-top: 15px; margin-right:70px;">
            </div>
           <div id ="rcorner-right">
                <div class="pull-health">
                        อายุ : {{elder.elder_age}} ปี<br> 
                        กรุ๊ปเลือด : {{elder.elder_blood}}<br> 
                        น้ำหนัก : {{elder.elder_weight}} กก.<br>
                        ส่วนสูง : {{elder.elder_height}} ซม.<br>
                        โรคประจำตัว : {{elder.elder_disease}}<br>
                        ยาที่ใช้ประจำ : {{elder.elder_useMedicine}}<br>
                        ยาที่แพ้ : {{elder.elder_medicine}}<br>
                        อาหารที่แพ้ : {{elder.elder_food}}<br>                 
                </div>
           </div>
        </div>

            <div class = "help">
                <img src="{% static '/assets/img/medical.png' %}" alt="logo" width="150" height="150">
            </div>
            <div class="help2">
                วิธีให้ความช่วยเหลือ
            </div>   

        <div id="rcorner-center">
            <div class = "in_help1">
                <p>ประวัติการรักษา : {{elder.elder_cure}}</p>
                <p>วิธีให้ความช่วยเหลือ : {{elder.elder_help}}</p>
            </div>
        </div>


            <div class = "other">
                <img src="{% static '/assets/img/favourite.png' %}" alt="logo" width="150" height="150">
            </div>
            <div class="help2">
                ข้อมูลอื่น ๆ
            </div>


        <div id="square-left">
            <div class = "in_other">
                <img src="{% static '/assets/img/home-address.png' %}" alt="logo" width="100" height="100">
            </div>
            <div class="oth">
                ที่อยู่
            </div>
            <div style="font-family: 'Sukhumvit Set';font-size: 25px;">
                {{elder.elder_address}}
            </div>
           
        </div>

        <div id="square-right">
            <div class = "in_other">
                <img src="{% static '/assets/img/lover.png' %}" alt="logo" width="100" height="100">
            </div>
            <div class="oth">
                สิ่งที่ชอบ
            </div> 
            <div style="font-family: 'Sukhumvit Set';font-size: 25px;text-align:center; margin-left: 10px;">
                <div>เพลงที่ชอบ : {{elder.elder_song}}</div>

                <div style="margin-top: 15px;">ดาราที่ชอบ : {{elder.elder_star}}</div>
                
                <div style="margin-top: 15px;">ภาพยนตร์ที่ชอบ : {{elder.elder_movie}}</div>
               
            </div> 
        </div>

        </body>
</html>